service: lambda-chatgpt
plugins: []
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  versionFunctions: false
  environment:
    OPENAI_KEY: ${env:OPENAI_KEY}


functions:
  getjoke:
    handler: src/handler.main
    url: true